import type { PropertyDetails } from "@ai-re-agent/contracts";
import type { ListingAdapter, ListingObservation } from "../types.js";

const base: PropertyDetails = {
  title: "",
  description: "",
  countryCode: "GR",
  city: "",
  neighborhood: "",
  region: "",
  address: null,
  unit: "entire plot",
  floor: 0,
  type: "house",
  transaction: "sale",
  active: true,
  priceEur: 220_000,
  areaSqm: 100,
  landSqm: 1600,
  bedrooms: 2,
  condition: "good",
  road: "paved",
  permits: "documents-listed",
  electricity: true,
  mainsWater: true,
  internet: true,
  townMinutes: 10,
  latitude: null,
  longitude: null,
  locationAccuracy: "approximate",
  photo: "stone",
  features: {
    secondUnit: false,
    seaView: false,
    barn: false,
    trees: true,
    pool: false,
    well: false,
    solar: false,
  },
};
// Fictional properties and claims. Coordinates point near towns, not actual parcels.
// Images illustrate a visual mood only; they do not show these fictional listings.
const properties: PropertyDetails[] = [
  {
    ...base,
    title: "A stone home among the olives",
    city: "Καρδαμύλη",
    neighborhood: "Kardamyli",
    region: "Messinia",
    address: "Δείγμα Μεσσηνίας 1",
    priceEur: 248_000,
    areaSqm: 104,
    landSqm: 2400,
    latitude: 36.886,
    longitude: 22.233,
    townMinutes: 8,
    photo: "stone",
    features: {
      ...base.features,
      barn: true,
      well: true,
      solar: true,
      seaView: true,
    },
    description:
      "A simple stone home, established olive trees and a separate old stable. The sample describes paved access and utility connections, with permit documents available to request.",
  },
  {
    ...base,
    title: "Room for a slower kind of life",
    city: "Βάμος",
    neighborhood: "Vamos",
    region: "Crete",
    address: "Δείγμα Χανίων 2",
    priceEur: 235_000,
    areaSqm: 96,
    landSqm: 1850,
    latitude: 35.407,
    longitude: 24.199,
    townMinutes: 7,
    photo: "garden",
    features: { ...base.features, secondUnit: true, solar: true, pool: true },
    description:
      "A quiet garden, a modest house and a separate guest unit. The sample includes solar panels and a small pool, a short reported drive from town.",
  },
  {
    ...base,
    title: "A farmhouse with space to grow",
    city: "Αίγιο",
    neighborhood: "Aigio",
    region: "Achaia",
    address: "Δείγμα Αχαΐας 3",
    priceEur: 189_000,
    areaSqm: 112,
    landSqm: 3200,
    latitude: 38.213,
    longitude: 22.075,
    townMinutes: 9,
    photo: "village",
    features: { ...base.features, barn: true, well: true, solar: true },
    description:
      "Room for an orchard and an existing barn. This fictional listing reports year-round road access, a working well and utilities.",
  },
  {
    ...base,
    title: "A little green corner of Corfu",
    city: "Δουκάδες",
    neighborhood: "Doukades",
    region: "Corfu",
    address: "Δείγμα Κέρκυρας 4",
    priceEur: 265_000,
    areaSqm: 88,
    landSqm: 1400,
    latitude: 39.688,
    longitude: 19.742,
    townMinutes: 12,
    photo: "cottage",
    permits: "reported",
    features: { ...base.features, secondUnit: true, pool: true },
    description:
      "A compact house with a shaded garden and room for guests. Permits are only reported in the sample; documentation needs checking.",
  },
  {
    ...base,
    title: "A hillside home, a glimpse of sea",
    city: "Κύμη",
    neighborhood: "Kymi",
    region: "Evia",
    address: "Δείγμα Εύβοιας 5",
    priceEur: 215_000,
    areaSqm: 120,
    landSqm: 2100,
    latitude: 38.634,
    longitude: 24.094,
    townMinutes: 10,
    photo: "coast",
    features: { ...base.features, seaView: true, barn: true },
    description:
      "A home with a sea-facing outlook and an old outbuilding. Tree cover is an amenity in the sample, not an assessment of wildfire exposure.",
  },
  {
    ...base,
    title: "An old house with a new chapter",
    city: "Πλωμάρι",
    neighborhood: "Plomari",
    region: "Lesvos",
    address: "Δείγμα Λέσβου 6",
    priceEur: 145_000,
    areaSqm: 78,
    landSqm: 1700,
    latitude: 38.992,
    longitude: 26.368,
    townMinutes: 8,
    photo: "cottage",
    condition: "needs-renovation",
    permits: "reported",
    internet: null,
    features: { ...base.features, seaView: true, well: true },
    description:
      "A smaller house to restore, with established fruit trees. Renovation cost and internet service are unknown; neither is implied by the score.",
  },
  {
    ...base,
    title: "An olive grove to make your own",
    city: "Κορώνη",
    neighborhood: "Koroni",
    region: "Messinia",
    address: "Δείγμα Μεσσηνίας 7",
    priceEur: 95_000,
    areaSqm: 0,
    landSqm: 4100,
    bedrooms: 0,
    type: "land",
    latitude: 36.821,
    longitude: 21.944,
    townMinutes: 9,
    photo: "olive",
    permits: "unknown",
    electricity: null,
    mainsWater: null,
    internet: null,
    features: { ...base.features, well: true },
    description:
      "Land with established olive trees and paved access, with no existing house. Buildability and any future building permission are unknown and must be researched.",
  },
  {
    ...base,
    title: "A garden retreat near Pelion",
    city: "Μηλιές",
    neighborhood: "Milies",
    region: "Pelion",
    address: "Δείγμα Πηλίου 8",
    priceEur: 228_000,
    areaSqm: 102,
    landSqm: 1900,
    latitude: 39.329,
    longitude: 23.151,
    townMinutes: 11,
    photo: "garden",
    road: "unknown",
    description:
      "A promising garden home, but the sample does not describe the last stretch of road. Kept apart from matches until paved access is confirmed.",
  },
  {
    ...base,
    title: "Island light, room to breathe",
    city: "Φιλώτι",
    neighborhood: "Filoti",
    region: "Naxos",
    address: "Δείγμα Νάξου 9",
    priceEur: 285_000,
    areaSqm: 93,
    landSqm: null,
    latitude: 37.05,
    longitude: 25.498,
    townMinutes: 8,
    photo: "coast",
    features: { ...base.features, seaView: true, solar: true },
    description:
      "A modest island house with a reported sea view. The plot size is absent, so it needs checking before it can meet the essentials.",
  },
  {
    ...base,
    title: "A coastal house above budget",
    city: "Πύλος",
    neighborhood: "Pylos",
    region: "Messinia",
    address: "Δείγμα Μεσσηνίας 10",
    priceEur: 335_000,
    latitude: 36.913,
    longitude: 21.696,
    photo: "stone",
    description:
      "Excluded from the shortlist because the asking price is above €300,000.",
  },
  {
    ...base,
    title: "A village house on a small plot",
    city: "Λεωνίδιο",
    neighborhood: "Leonidio",
    region: "Arcadia",
    address: "Δείγμα Αρκαδίας 11",
    landSqm: 650,
    latitude: 37.167,
    longitude: 22.858,
    photo: "village",
    description:
      "Excluded from the shortlist because the plot is below 1,000 m².",
  },
  {
    ...base,
    title: "A country home off the beaten path",
    city: "Σκόπελος",
    neighborhood: "Skopelos",
    region: "Sporades",
    address: "Δείγμα Σκοπέλου 12",
    road: "unpaved",
    latitude: 39.1,
    longitude: 23.726,
    photo: "olive",
    description:
      "Excluded from the shortlist because the access road is unpaved.",
  },
];

// Stable source/external IDs intentionally update the original demo on the next import.
export const sampleAthens: ListingAdapter = {
  id: "sample-athens",
  name: "Hellenic Homes · demo",
  async fetchListings() {
    return properties.map(
      (property, i): ListingObservation => ({
        ...property,
        sourceId: this.id,
        sourceName: this.name,
        externalId: `ath-${i + 1}`,
        url: `https://hellenic-homes.example/listings/${i + 1}?utm_source=sample`,
        observedAt: "2026-10-08T09:00:00.000Z",
      }),
    );
  },
};
export const sampleAttica: ListingAdapter = {
  id: "sample-attica",
  name: "Open Door Greece · demo",
  async fetchListings() {
    return properties.slice(0, 3).map(
      (property, i): ListingObservation => ({
        ...property,
        address: property.address!.toLocaleUpperCase("el-GR"),
        priceEur: i === 0 ? 245_000 : property.priceEur,
        sourceId: this.id,
        sourceName: this.name,
        externalId: `att-${i + 101}`,
        url: `https://open-door.example/property/${i + 101}`,
        observedAt: "2026-10-09T09:00:00.000Z",
      }),
    );
  },
};
